### Fixed Point Iteraration

In [61]:
import math
import pandas as pd

In [62]:
def print_iterations(it_list):
  df = pd.DataFrame(it_list, columns=['it','p_n']) 
  pd.options.display.float_format = '{:,.9f}'.format
  display(df)

In [63]:
# Define a few possible functions whose fixed point equals the zero of f(x)=x**3+4*x**2-10
def g_a(x):
    return x-x**3-4*x**2+10
def g_b(x):
    return math.sqrt(10.0/x - 4*x)
def g_c(x):
    return 0.5*math.sqrt(10-x**3)
def g_d(x):
    return math.sqrt(10.0/(4+x))
def g_e(x):
    return x - (x**3+4*x**2-10)/(3*x**2+8*x)

In [66]:
def solve_fixed_point(g,p0,tol=1.0e-7,it_max=30):
    """Implements the fixed point iteration algorithm 

    Args:
        g (function): the function defining the fixed point iteration
        p0 (double): initial approximation of the fixed point
        tol (tolerance): numerical tolerance for absolute error between successive iterations. Defaults to 1.0e-7
        it_max (int): maximum allowable number of iterations. Defaults to 30

    Raises:
        RuntimeError: Raises exception when algorithm does not converge after it_max iterations

    Returns:
        double: approximate fixed point
    """
    # Initialize the iteratino count
    it_count = 1
    # Fixed point iteration loop
    it_list = [[0,p0]]
    while (it_count <=it_max):
        # Update p
        try:
          p=g(p0)
        except Exception as err:
          print('ERROR: ',err)
          return p0,it_list
        # Store new iterate
        it_list.append([it_count,p])
        # Check exit condition
        if(math.fabs(p-p0)<tol):
            return p,it_list
        # Update iteration count
        it_count += 1
        # Update current iterate
        p0=p
    # If the algorithm does not converge in it_max iterations then raise exception
    print(("ERROR: Solution not found after {} iterations").format(it_max))
    return p0,it_list

In [67]:
# Set initial approximation 
p0 = 1.5

# Use g_a
p_a, it_list_a = solve_fixed_point(g_a,p0)
print('Approximate solution of the fixed point equation: ',p_a)
print_iterations(it_list_a)

# Use g_b
p_b, it_list_b = solve_fixed_point(g_b,p0)
print('Approximate solution of the fixed point equation: ',p_b)
print_iterations(it_list_b)

# Use g_c
p_c, it_list_c = solve_fixed_point(g_c,p0)
print('Approximate solution of the fixed point equation: ',p_c)
print_iterations(it_list_c)

# Use g_d
p_d, it_list_d = solve_fixed_point(g_d,p0)
print('Approximate solution of the fixed point equation: ',p_d)
print_iterations(it_list_d)

# Use g_e
p_e, it_list_e = solve_fixed_point(g_e,p0)
print('Approximate solution of the fixed point equation: ',p_e)
print_iterations(it_list_e)

ERROR:  (34, 'Numerical result out of range')
Approximate solution of the fixed point equation:  -2.082712908581025e+216

   it                                                p_n
0   0                                        1.500000000
1   1                                       -0.875000000
2   2                                        6.732421875
3   3                                     -469.720012002
4   4                              102,754,555.187385112
5   5       -1,084,933,870,531,746,352,594,944.000000000
6   6 1,277,055,591,444,378,074,254,579,861,314,550,1...
7   7 -2,082,712,908,581,024,997,457,179,183,627,809,...

ERROR:  math domain error
Approximate solution of the fixed point equation:  2.99690880578722

   it         p_n
0   0 1.500000000
1   1 0.816496581
2   2 2.996908806

Approximate solution of the fixed point equation:  1.365229983524674

    it         p_n
0    0 1.500000000
1    1 1.286953768
2    2 1.402540804
3    3 1.345458374
4    4 1.375170253
5    5 1.360094193
6    6 1.367846968
7    7 1.363887004
8    8 1.365916733
9    9 1.364878217
10  10 1.365410061
11  11 1.365137821
12  12 1.365277209
13  13 1.365205850
14  14 1.365242384
15  15 1.365223680
16  16 1.365233256
17  17 1.365228353
18  18 1.365230863
19  19 1.365229578
20  20 1.365230236
21  21 1.365229899
22  22 1.365230072
23  23 1.365229984

Approximate solution of the fixed point equation:  1.3652300225155685

   it         p_n
0   0 1.500000000
1   1 1.348399725
2   2 1.367376372
3   3 1.364957015
4   4 1.365264748
5   5 1.365225594
6   6 1.365230576
7   7 1.365229942
8   8 1.365230023

Approximate solution of the fixed point equation:  1.3652300134140969

   it         p_n
0   0 1.500000000
1   1 1.373333333
2   2 1.365262015
3   3 1.365230014
4   4 1.365230013